# Site settings
title: Damian Bogunowicz - dtransposed
email: damian.bogunowicz
description: "Engineering, Robotics, AI, Technology"
#baseurl: "http://dtransposed.github.io"
url: "http://dtransposed.github.io"
linkedin_username: dbogunowicz
twitter_username: dtransposed
github_username:  dtransposed

# Disqus
disqus:
    shortname: dtransposed
# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
plugins:
  - jekyll-katex
