# Site settings
title: Damian Bogunowicz - dtransposed
email: damian.bogunowicz
description: "Engineering, Robotics, AI, Technology"
baseurl: ""
url: "http://dtransposed.github.io"
linkedin_username: dbogunowicz
twitter_username: dtransposed
github_username:  dtransposed

# Build settings
markdown: kramdown
permalink: pretty
# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: dtransposed

highlighter: rouge
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
plugins:
  - jekyll-katex
